name: Deploy and Destroy EKS Cluster

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.8  # Use the version you need

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Terraform Init
      run: terraform init
      working-directory: EKS

    - name: Terraform Validate
      run: terraform validate
      working-directory: EKS

    - name: Terraform Plan
      run: terraform plan
      working-directory: EKS

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: EKS

    - name: Terraform Destroy (optional)
      run: terraform destroy -auto-approve
      working-directory: EKS
      if: ${{ github.event.inputs.destroy == 'true' }}
