name: Deploy EKS Cluster

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.8  # Use the version you need

    - name: Terraform Init
      run: terraform init
      working-directory: EKS  # Change this to your EKS cluster folder

    - name: Terraform Validate
      run: terraform validate
      working-directory: EKS  # Change this to your EKS cluster folder

    - name: Terraform Plan
      run: terraform plan
      working-directory: EKS  # Change this to your EKS cluster folder
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: EKS  # Change this to your EKS cluster folder
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
